# Generated by Django 3.1.5 on 2021-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='./react/src/media')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
