# Generated by Django 3.1.5 on 2021-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проект'},
        ),
        migrations.AlterField(
            model_name='service',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Введите название проекта'),
        ),
    ]
