# Generated by Django 3.1.5 on 2021-02-08 04:30

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210206_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to=mainapp.models.upload_to, verbose_name='Image'),
        ),
    ]
