# Generated by Django 3.1.5 on 2021-02-08 06:44

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210208_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to=mainapp.models.upload_to, verbose_name='Image'),
        ),
    ]
