# Generated by Django 3.1.5 on 2021-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210209_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('date', models.CharField(max_length=255, verbose_name='Когда удобно позвонить')),
                ('only_massage', models.BooleanField(verbose_name='Только позвонить')),
            ],
            options={
                'verbose_name': 'Заказ звонка',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
