# Generated by Django 3.1.5 on 2021-02-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='only_massage',
            field=models.CharField(max_length=50, verbose_name='Только позвонить'),
        ),
    ]
